import http from "node:http";

const PORT = Number(process.env.PORT || 8787);
const API_KEY = process.env.TYPESAFE_API_KEY;
if (!API_KEY) { console.error("Missing TYPESAFE_API_KEY."); process.exit(1); }

const STOP = new Set(["does","do","is","are","was","were","the","a","an","this","that","page","document","mention","mentions","have","has","there","any","about","on","of","to","for","in","and","or","with","what","which","where","when","can","could","will","would","should","tell","me"]);
const normalize=s=>String(s||"").toLowerCase().replace(/\s+/g," ").trim();
const terms=q=>normalize(q).split(/[^a-z0-9₹%]+/).filter(x=>x.length>2&&!STOP.has(x));
function candidates(content,question){const chunks=String(content).replace(/\r/g,"").split(/\n{2,}|(?<=[.!?।])\s+/).map(x=>x.trim()).filter(x=>x.length>=25);const ts=terms(question);return chunks.map((text,index)=>{const n=normalize(text);const hits=ts.reduce((n,t)=>n+(n.includes(t)?1:0),0);return{id:"p_"+index,text,lexical:ts.length?hits/ts.length:0}}).sort((a,b)=>b.lexical-a.lexical).slice(0,18)}
async function jev(state,questions){const r=await fetch("https://api.typesafe.ai/v1/systemone",{method:"POST",headers:{"Authorization":"Bearer "+API_KEY,"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({model:"jev-latest",state,questions})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||b?.message||"TypeSafe API request failed");return b}
async function ask({question,content,title="",url=""}){if(!question||!content)throw new Error("question and content are required");if(String(content).length>120000)throw new Error("Page is too large.");const pool=candidates(content,question);const p=await jev({question,page:{title,url,content:String(content).slice(0,80000)},candidate_passages:pool.map(({id,text})=>({id,text}))},{answer_found:{type:"noul",instructions:"Does the provided page content contain a passage that directly answers the user's question? Answer yes only when sufficient information is present, not merely related words.",criteria:{yes:"A passage directly answers the user's question.",no:"The page does not contain sufficient information to answer it."}}});const probability=p?.answers?.answer_found?.noul??0;if(Number(probability)<0.5)return{answer_found:false,probability,evidence:null};if(!pool.length)return{answer_found:true,probability,evidence:null};const e=await jev({question,candidate_passages:pool.map(({id,text})=>({id,text}))},{best_evidence:{type:"choice",instructions:"Which candidate passage most directly answers the question? Choose no_match if none provides enough information.",criteria:Object.fromEntries([...pool.map(x=>[x.id,x.text.slice(0,500)]),["no_match","No candidate provides sufficient evidence."]])}});const match=pool.find(x=>x.id===e?.answers?.best_evidence?.choice);return{answer_found:true,probability,evidence:match?{text:match.text,id:match.id}:null}}
const server=http.createServer(async(req,res)=>{res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type");res.setHeader("Access-Control-Allow-Methods","POST, OPTIONS");if(req.method==="OPTIONS")return res.writeHead(204).end();if(req.method!=="POST"||req.url!=="/api/ask")return res.writeHead(404,{"Content-Type":"application/json"}).end(JSON.stringify({error:"Not found"}));let raw="";req.on("data",c=>{raw+=c;if(raw.length>500000)req.destroy()});req.on("end",async()=>{try{const result=await ask(JSON.parse(raw));res.writeHead(200,{"Content-Type":"application/json"}).end(JSON.stringify(result))}catch(e){res.writeHead(400,{"Content-Type":"application/json"}).end(JSON.stringify({error:e.message||"Request failed"}))}})});
server.listen(PORT,"127.0.0.1",()=>console.log("Jev local server: http://127.0.0.1:"+PORT+"/api/ask"));